site_name: 神州数码IT帮助文档(Beta)
#site_url: https://it.digitalchina.com

# Repository
repo_name: cnravin/documentation
repo_url: https://github.com/cnravin/documentation
edit_uri: "edit/main/docs/"

# Copyright
copyright: Copyright &copy; 2000 - 2021 DigitalChina

theme:
  #custom_dir: !ENV [THEME_DIR, "theme"]
  custom_dir: theme
  name: material
  
  font: false

  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - scheme: default
      primary: light blue
      toggle:
        icon: weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: weather-night
        name: Switch to light mode
  favicon: assets/favicon.ico
  logo: assets/logo.gif

extra_css:
  - css/kbd_extra.css
  - css/extra.css
  - css/roboto.css

# Extensions
markdown_extensions:
  - admonition
  - meta
  - def_list
  - kbdextension:
      brackets_css: button-css
      enable_braces: true
      braces_css: menu-css
      enable_parens: true
      parens_css: keyboard-css
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: cnravin
      repo: documentation
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true


# Page tree
nav:
  - Home: index.md
  - Guides:
    - VPN:
      - guides/anyconnect.md
      - guides/vpn-install.md
    - Network:
      - guides/wireless_setting.md
      - guides/intel_wifi.md
  - Downlods:
      - download/index.md
